language: cpp
compiler: gcc

dist: xenial
addons:
  apt:
    packages:
    - libboost-dev
    - qt5-default

script:
- qmake
- make -j$(nproc)

branches:
  except:
  - continuous

before_deploy:
- git tag continuous

deploy:
  provider: releases
  api_key:
    secure: icmBxMxb+dxeNlcXnEzcU8ZE5NrDcwtYALZYAzvgKdL0WxAFAbgKKcx2wN7pAbY34wQsfafYPnMx2Indbkd0/9EE4cFvqvupX8MUe1b6mMGiYXEPJ4z8jYhgeMUcAFct4JPIOV7GXb8hYfUYH+VfgfFWT7XlZSkMdD/pdN/7osCyEW3nx/d8VXbqw9URhVapaO+Po2ZOkP2sVjzHkT7I/a17riwBlpb61GuuTqsPhjGNNNIdTTXLQ2hnMBpJoS1M0fV57PXzgGciRiGRlirdvTu+G3tWQfnOleupfrjX+hewzUH6I1WCn48jEpwMJmNDHo/YNDzYYOxiVvB4giUFDbf0iX5NbXDIl8Dq4fQAlOAMw7E6xyrTypqpmlka/TuCItDMaubbCAZoots4oZ+jN6r5bgJ+tfpRUR9d0OcHpm7mq4IzBebm152gpqmg32FYSs5Rcdq4kZKpdYT9CCH+qGQZmqLXDD4ZL8E2Bn7nXre45rJztYsFkGhJjz6hGb4vUr+ROEPTWYVOl5jKg1KkxgezOcaom7Qj1+XzbPezTOnNoaBgwyIx/2cuFFTW3z3+L1I+yWE0CoAKmUe5/g3UHXP+oBO3wGMIH5zXsMU7SzJRxg/TMBmXjG1UXFbF/5pNFkGb3ok5N1VGFJYxY6N/g3K9ddX801hkUOkT2/5yUs4=
  file:
    - $TRAVIS_BUILD_DIR/QMediathekView
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    branch: master
  on:
    repo: adamreichold/QMediathekView
