language: cpp
compiler: gcc

dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt593-trusty'
    packages:
    - libboost1.55-dev
    - qt59base
    - qt59svg

script:
- . /opt/qt*/bin/qt*-env.sh
- qmake
- make -j`nproc`
- make INSTALL_ROOT=appdir install

after_success:
- wget --continue --no-verbose "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
- unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
- VERSION=`git rev-parse --short HEAD` ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -extra-plugins=iconengines/libqsvgicon.so
- wget --continue --no-verbose "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
- test $TRAVIS_BRANCH = master && bash upload.sh QMediathekView*.AppImage*

branches:
  except:
  - continuous
