language: cpp
compiler: gcc

dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt593-trusty'
    packages:
    - qt59base
    - qt59svg

cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/build/internals

before_script:
- wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
- chmod +x rustup-init
- ./rustup-init -y --profile minimal
- . $HOME/.cargo/env

script:
- . /opt/qt*/bin/qt*-env.sh
- mkdir -p build
- cd build
- qmake ..
- make -j`nproc`
- make INSTALL_ROOT=../appdir install
- cd ..

after_success:
- wget --continue --no-verbose "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
- chmod a+x linuxdeployqt-continuous-x86_64.AppImage
- unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
- VERSION=`git rev-parse --short HEAD` ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/QMediathekView.desktop -appimage -extra-plugins=iconengines
- wget --continue --no-verbose "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
- test $TRAVIS_BRANCH = master && bash upload.sh QMediathekView*.AppImage*

branches:
  except:
  - continuous
