on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: source .github/scripts/build.sh
      shell: bash
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: continuous
        force_push_tag: true
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        removeArtifacts: true
        tag: continuous
        name: Continuous build
        body: AppImage built automatically from latest commit.
        prerelease: true
        artifacts: "QMediathekView*.AppImage*"
        token: ${{ secrets.GITHUB_TOKEN }}
