on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: source .github/scripts/build.sh
      shell: bash
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        removeArtifacts: true
        tag: continuous
        name: Continuous build
        prerelease: true
        artifacts: "QMediathekView*.AppImage*"
        token: ${{ secrets.GITHUB_TOKEN }}
